# Generated by Django 2.1.7 on 2019-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
