# Generated by Django 2.1.7 on 2019-04-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_picture_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='identificado',
            field=models.BooleanField(default=False),
        ),
    ]
