# Generated by Django 2.1.7 on 2019-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_picture_identificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='no_dicom',
            field=models.BooleanField(default=False),
        ),
    ]
