# Generated by Django 2.1.7 on 2019-03-09 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0002_picture_anonimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campos_defecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.PositiveIntegerField(blank=True, null=True)),
                ('v_esperado', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('medidas', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campostagimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('medidas', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('precision', models.PositiveIntegerField(blank=True, null=True)),
                ('v_esperado', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('cumple', models.NullBooleanField(default=None)),
            ],
            options={
                'permissions': (('can_ver_parametrosimg', 'puede ver parametrosimg'),),
            },
        ),
        migrations.CreateModel(
            name='Tagsdicom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tag', models.CharField(max_length=75)),
                ('name_tag', models.CharField(max_length=200)),
                ('key_tag', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoimagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('nombre_aux', models.CharField(blank=True, default='', max_length=75, null=True)),
                ('mostrar', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='campostagimg',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes'),
        ),
        migrations.AddField(
            model_name='campostagimg',
            name='img_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture'),
        ),
        migrations.AddField(
            model_name='campostagimg',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tagsdicom'),
        ),
        migrations.AddField(
            model_name='campostagimg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campos_defecto',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes'),
        ),
        migrations.AddField(
            model_name='campos_defecto',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tagsdicom'),
        ),
        migrations.AddField(
            model_name='campos_defecto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
