# Generated by Django 2.1.7 on 2019-03-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campostagimg',
            name='visible',
        ),
    ]
