# Generated by Django 2.1.7 on 2019-03-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_picture_anonimo'),
        ('validacion', '0002_remove_campostagimg_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrosmotioncorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_func', models.CharField(max_length=50, null=True)),
                ('relative_func', models.CharField(max_length=50, null=True)),
                ('graphic_desplazamiento_func', models.CharField(blank=True, max_length=300, null=True)),
                ('graphic_rotacion_func', models.CharField(blank=True, max_length=300, null=True)),
                ('graphic_traslacion_func', models.CharField(blank=True, max_length=300, null=True)),
                ('aceptado_func', models.NullBooleanField()),
                ('imagen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture')),
            ],
        ),
    ]
