# Generated by Django 2.1.7 on 2019-03-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_picture_anonimo'),
        ('validacion', '0003_parametrosmotioncorrect'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_to_show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes')),
                ('sujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture')),
            ],
            options={
                'permissions': (('can_ver_slice', 'puede ver slice'),),
            },
        ),
    ]
