# Generated by Django 2.1.7 on 2019-04-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0004_img_to_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenesdefecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterModelOptions(
            name='img_to_show',
            options={'ordering': ['path'], 'permissions': (('can_ver_slice', 'puede ver slice'),)},
        ),
        migrations.AddField(
            model_name='img_to_show',
            name='img_defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacion.Imagenesdefecto'),
        ),
    ]
