# Generated by Django 2.1.7 on 2019-03-10 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('validacion', '0003_parametrosmotioncorrect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pathscript', models.CharField(max_length=150)),
                ('habilitado', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='procesamiento.Task')),
                ('tipo_imagen', models.ForeignKey(on_delete=None, to='validacion.Tipoimagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Taskgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='procesamiento.Taskgroup')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.Task')),
                ('tipo_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes')),
            ],
        ),
    ]
