# Generated by Django 2.1.7 on 2019-03-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='orden',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='task',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='task',
            field=models.ManyToManyField(blank=True, to='procesamiento.Task'),
        ),
    ]
