# Generated by Django 2.1.7 on 2019-03-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0002_auto_20190315_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='dependencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesamiento.Taskgroup'),
        ),
    ]
