# Generated by Django 2.1.7 on 2019-03-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0004_img_to_show'),
        ('procesamiento', '0003_auto_20190315_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=200, null=True)),
                ('dependencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesamiento.Pipeline')),
                ('grupos', models.ManyToManyField(blank=True, to='procesamiento.Taskgroup')),
                ('tipo_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.Tipoimagenes')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='dependencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesamiento.Task'),
        ),
    ]
