# Generated by Django 2.1.7 on 2019-03-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0004_auto_20190316_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='eliminable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='eliminable',
            field=models.BooleanField(default=True),
        ),
    ]
