# Generated by Django 2.1.7 on 2019-03-17 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_picture_anonimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procesamiento', '0005_auto_20190316_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_celery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.Pipeline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
