# Generated by Django 2.1.7 on 2019-04-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0005_auto_20190427_2242'),
        ('fileupload', '0003_picture_identificado'),
        ('procesamiento', '0012_auto_20190428_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas', models.ManyToManyField(to='validacion.img_to_show')),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileupload.Picture')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.Pipeline')),
            ],
        ),
        migrations.RemoveField(
            model_name='task_celery',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='task_celery',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='task_celery',
            name='configuracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procesamiento.config'),
        ),
    ]
